
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadSession() : Promise<Result<SessionData | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSession(session: SessionData) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_session", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPublicationOptions(publicationOptions: PublicationOptions) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_publication_options", { publicationOptions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initMockState(workspacePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_mock_state", { workspacePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async selectFolder() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async selectFile(title: string, filters: ([string, string[]])[]) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_file", { title, filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openBrowser(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_browser", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanBooks(path: string) : Promise<Result<BookInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_books", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadCoverImage(coverPath: string | null) : Promise<Result<CoverStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_cover_image", { coverPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadBookMetadata(bookPath: string) : Promise<Result<BookMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_book_metadata", { bookPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveBookMetadata(bookPath: string, metadata: BookMetadata) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_book_metadata", { bookPath, metadata }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAutocompleteAuthors(books: BookInfo[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_autocomplete_authors", { books }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAutocompleteSeries(books: BookInfo[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_autocomplete_series", { books }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async replaceCoverImage(bookPath: string, newCoverPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_cover_image", { bookPath, newCoverPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBookOutputs(bookPath: string) : Promise<Result<BookOutputLink[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_book_outputs", { bookPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startProcessing(books: BookInfo[], publishEnabled: boolean, wordStatsEnabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_processing", { books, publishEnabled, wordStatsEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addBook(workspaceRoot: string, sourceMd: string) : Promise<Result<AddBookResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_book", { workspaceRoot, sourceMd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkDuplicate(workspaceRoot: string, mdFilename: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_duplicate", { workspaceRoot, mdFilename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteBook(bookPath: string, workspaceRoot: string) : Promise<Result<BookInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_book", { bookPath, workspaceRoot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeBookFile(bookPath: string, newSource: string, workspaceRoot: string) : Promise<Result<ChangeBookResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_book_file", { bookPath, newSource, workspaceRoot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBookAnalysis(bookPath: string, forceRefresh: boolean) : Promise<Result<AnalysisResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_book_analysis", { bookPath, forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubDeviceFlowStart() : Promise<Result<DeviceFlowInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_device_flow_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubDeviceFlowPoll(deviceCode: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_device_flow_poll", { deviceCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubStoreToken(token: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_store_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubCheckAuth() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_check_auth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubLogout() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleAuthStart() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_auth_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleAuthCancel() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_auth_cancel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleCheckAuth() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_check_auth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleLogout() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleListDocs() : Promise<Result<GoogleDocInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_list_docs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleLinkDoc(bookPath: string, docId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_link_doc", { bookPath, docId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleSyncDoc(bookPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_sync_doc", { bookPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleSyncSelected(books: BookInfo[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_sync_selected", { books }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async googleUnlinkDoc(bookPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_unlink_doc", { bookPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitCheckInitialized(workspacePath: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_check_initialized", { workspacePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitCloneRepository(githubUrl: string, workspacePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_clone_repository", { githubUrl, workspacePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitSync(workspacePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_sync", { workspacePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitSave(workspacePath: string, message: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_save", { workspacePath, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitResetLocalChanges(workspacePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_reset_local_changes", { workspacePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitGetLog(workspacePath: string, limit: number) : Promise<Result<GitCommit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_get_log", { workspacePath, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitGetStatus(workspacePath: string) : Promise<Result<GitSyncStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_get_status", { workspacePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitGetRemoteUrl(workspacePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_get_remote_url", { workspacePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitGetRevisionDiffs(workspacePath: string, commitHash: string) : Promise<Result<RevisionDiff[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_get_revision_diffs", { workspacePath, commitHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitGetLocalDiffs(workspacePath: string) : Promise<Result<RevisionDiff[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_get_local_diffs", { workspacePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBookProcessingDiff(bookPath: string) : Promise<Result<DiffComparison, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_book_processing_diff", { bookPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check for updates and install if available
 */
async checkForUpdates() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_updates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
bookListChangedEvent: BookListChangedEvent,
coverReloadEvent: CoverReloadEvent,
gitOperationProgressEvent: GitOperationProgressEvent,
googleDocsBatchSyncUpdateEvent: GoogleDocsBatchSyncUpdateEvent,
googleDocsProgressEvent: GoogleDocsProgressEvent,
processingUpdateEvent: ProcessingUpdateEvent,
updateProgressEvent: UpdateProgressEvent
}>({
bookListChangedEvent: "book-list-changed-event",
coverReloadEvent: "cover-reload-event",
gitOperationProgressEvent: "git-operation-progress-event",
googleDocsBatchSyncUpdateEvent: "google-docs-batch-sync-update-event",
googleDocsProgressEvent: "google-docs-progress-event",
processingUpdateEvent: "processing-update-event",
updateProgressEvent: "update-progress-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Result of adding a book to the workspace
 */
export type AddBookResult = { book_path: string; is_duplicate: boolean; books: BookInfo[]; new_book_index: number | null }
/**
 * Response from get_or_compute_analysis
 */
export type AnalysisResponse = { 
/**
 * The word analysis statistics
 */
stats: WordAnalysisStats; 
/**
 * Whether the result was loaded from cache (true) or freshly computed (false)
 */
was_cached: boolean; 
/**
 * Unix timestamp when the analysis was performed/cached (as f64 for JS compatibility)
 */
cache_timestamp: number }
/**
 * Information about a book file
 */
export type BookInfo = { path: BookPath; display_name: string; selected: boolean; cover_image_path: string | null; metadata: BookMetadata | null; google_docs_sync_info: GoogleDocsSyncInfo | null; 
/**
 * List of changed files (relative to book folder) with uncommitted git changes
 */
git_changed_files: string[] }
/**
 * Event to signal that the book list has changed and UI should refresh
 * Emitted after git operations that could modify the book list (clone, sync, save)
 */
export type BookListChangedEvent = Record<string, never>
/**
 * Book metadata from YAML frontmatter
 */
export type BookMetadata = { title?: string; author?: string; "belongs-to-collection"?: string | null; "group-position"?: number | null; language?: string | null; rights?: string | null; "cover-image"?: string | null; "replace-pairs"?: ReplacePair[] | null; identifier?: Identifier[] | null }
export type BookOutputFormat = "epub" | "pdf" | "azw3"
export type BookOutputLink = { format: BookOutputFormat; path: string }
/**
 * NewType wrapper for book file path
 */
export type BookPath = string
/**
 * Result of changing a book's source file
 */
export type ChangeBookResult = { new_book_path: string; books: BookInfo[]; updated_book_index: number | null }
/**
 * Event emitted when a cover should be reloaded
 * The UI should query cover status after receiving this event
 */
export type CoverReloadEvent = { book_path: string }
/**
 * Status of cover loading operation
 */
export type CoverStatus = 
/**
 * Not started loading yet
 */
{ type: "not_started" } | 
/**
 * Currently loading thumbnail
 */
{ type: "loading" } | 
/**
 * Thumbnail ready with data URL
 */
{ type: "ready"; data_url: string; width: number; height: number } | 
/**
 * Error during loading
 */
{ type: "error"; message: string }
/**
 * GitHub Device Flow information for UI display
 */
export type DeviceFlowInfo = { 
/**
 * Device code (internal, not shown to user)
 */
deviceCode: string; 
/**
 * User code to enter in browser
 */
userCode: string; 
/**
 * URL where user should authorize
 */
verificationUri: string; 
/**
 * Seconds until code expires
 */
expiresIn: number }
/**
 * Complete diff comparison result (manager output to UI)
 */
export type DiffComparison = { 
/**
 * Left display name for UI header
 */
left_display_name: DisplayName; 
/**
 * Right display name for UI header
 */
right_display_name: DisplayName; 
/**
 * Diff result with segments and statistics
 */
diff: DiffResult }
/**
 * Core diff result from engine (segments + statistics)
 */
export type DiffResult = { 
/**
 * List of diff segments with change types
 */
segments: DiffSegment[]; 
/**
 * Summary statistics of changes
 */
stats: WordChangeStats }
/**
 * Single segment in a word-level diff
 */
export type DiffSegment = { 
/**
 * Type of change (added/removed/unchanged)
 */
segment_type: SegmentType; 
/**
 * The text content of this segment
 */
text: string; 
/**
 * Context header (nearest preceding header) for this segment
 */
context_header: string | null }
/**
 * Display name for UI presentation (user-friendly label)
 */
export type DisplayName = string
/**
 * NewType wrapper for folder path in session
 */
export type FolderPath = string
/**
 * Git commit information
 */
export type GitCommit = { hash: string; message: string; author: string; timestamp: string }
/**
 * Event wrapper for git operation progress messages (for tauri-specta type-safe events)
 */
export type GitOperationProgressEvent = string
/**
 * Git synchronization status for UI display
 */
export type GitSyncStatus = 
/**
 * Repository not initialized (.git not present)
 */
{ status: "Uninitialized" } | 
/**
 * Working directory clean, in sync with remote
 */
{ status: "Clean" } | 
/**
 * Has commits that need to be pushed
 */
{ status: "NeedsPush" } | 
/**
 * Remote has commits that need to be pulled
 */
{ status: "NeedsPull" } | 
/**
 * Has uncommitted changes
 */
{ status: "Dirty" }
/**
 * Information about a Google Doc
 */
export type GoogleDocInfo = { id: string; name: string; modified_time: string }
/**
 * Events emitted during batch Google Docs sync
 */
export type GoogleDocsBatchSyncEvent = 
/**
 * Sync started for a book
 */
{ type: "started"; book_index: number; book_name: string } | 
/**
 * Progress update for a book
 */
{ type: "progress"; book_index: number; book_name: string; message: string } | 
/**
 * Book sync completed
 */
{ type: "completed"; book_index: number; book_name: string; success: boolean; message: string } | 
/**
 * All books synced
 */
{ type: "all_done"; total_books: number; success_count: number; fail_count: number }
/**
 * Event wrapper for batch Google Docs sync updates (for tauri-specta type-safe events)
 */
export type GoogleDocsBatchSyncUpdateEvent = GoogleDocsBatchSyncEvent
/**
 * Event wrapper for Google Docs sync progress messages (for tauri-specta type-safe events)
 */
export type GoogleDocsProgressEvent = string
/**
 * Google Docs sync information (stored in google-docs-sync.yaml)
 */
export type GoogleDocsSyncInfo = { "google-doc-id": string; "sync-status": string }
/**
 * Book identifier (e.g., ISBN)
 */
export type Identifier = { scheme?: string | null; text?: string | null }
/**
 * Events emitted during book processing (serializable for Tauri events)
 */
export type ProcessingEvent = 
/**
 * Processing started for a book
 */
{ type: "started"; book_index: number; book_name: string } | 
/**
 * Book processing completed
 */
{ type: "completed"; book_index: number; book_name: string; success: boolean; message: string; word_stats?: WordAnalysisStats | null; output_path?: string | null } | 
/**
 * All books processed
 */
{ type: "all_done" }
/**
 * Event wrapper for processing updates (for tauri-specta type-safe events)
 */
export type ProcessingUpdateEvent = ProcessingEvent
/**
 * Publication output options shared across UI and core processing flows.
 */
export type PublicationOptions = { embed_cover: boolean; epub: boolean; pdf: boolean; azw3: boolean }
/**
 * A single word replacement pair (case-sensitive, whole-word)
 */
export type ReplacePair = { source: string; target: string }
/**
 * Single file diff result from a git revision
 */
export type RevisionDiff = { 
/**
 * Relative file path in the repository
 */
file_path: string; 
/**
 * Complete diff comparison for this file
 */
comparison: DiffComparison }
/**
 * Type of diff segment for UI rendering
 */
export type SegmentType = 
/**
 * Text was added (green in UI)
 */
"added" | 
/**
 * Text was removed (red in UI)
 */
"removed" | 
/**
 * Text is unchanged (no highlighting)
 */
"unchanged"
/**
 * Session data to persist between application runs
 */
export type SessionData = { 
/**
 * Last selected folder path
 */
folder_path: FolderPath; 
/**
 * Paths of books that were selected
 */
selected_book_paths: BookPath[]; 
/**
 * Whether "Current Book" mode is enabled (actions apply to viewed book only)
 * Defaults to true for backward compatibility with existing session files
 */
current_book_mode?: boolean; 
/**
 * Persisted publication preferences.
 */
publication_options?: PublicationOptions }
/**
 * Update progress status
 */
export type UpdateProgress = { type: "Checking" } | { type: "NoUpdate" } | { type: "UpdateAvailable"; version: string } | { type: "Downloading"; percent: number } | { type: "Installing" } | { type: "Done" } | { type: "Error"; message: string }
/**
 * Event emitted during update progress
 */
export type UpdateProgressEvent = UpdateProgress
/**
 * Word analysis statistics for UI display
 */
export type WordAnalysisStats = { 
/**
 * Total words in document
 */
total_words: number; 
/**
 * Unique words after filtering
 */
unique_words: number; 
/**
 * Number of stopwords excluded
 */
excluded_count: number; 
/**
 * Top words with their counts (up to 100)
 */
top_words: ([string, number])[] }
/**
 * Word-level change statistics
 */
export type WordChangeStats = { 
/**
 * Number of words added
 */
added: number; 
/**
 * Number of words removed
 */
removed: number; 
/**
 * Number of words unchanged
 */
unchanged: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
