// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookInfo } from "./BookInfo";

/**
 * Result of adding a book to the workspace
 */
export type AddBookResult = { book_path: string, is_duplicate: boolean, books: Array<BookInfo>, new_book_index: number | null, };
