// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookInfo } from "./BookInfo";
import type { DeviceFlowInfo } from "./DeviceFlowInfo";
import type { GitAuthStatus } from "./GitAuthStatus";
import type { GitCommit } from "./GitCommit";
import type { GitSyncStatus } from "./GitSyncStatus";
import type { LogEntryPayload } from "./LogEntryPayload";
import type { ProcessingProgress } from "./ProcessingProgress";
import type { SessionData } from "./SessionData";

/**
 * Application actions for state management (Redux/Reducer style)
 * 
 * These actions match the frontend reducer actions to ensure type safety
 * between backend events and frontend state updates.
 */
export type AppAction = { "type": "SET_SESSION", "payload": SessionData | null } | { "type": "SET_BOOKS", "payload": Array<BookInfo> } | { "type": "SET_FOLDER", "payload": string | null } | { "type": "SET_PUBLISH_ENABLED", "payload": boolean } | { "type": "SET_WORD_STATS_ENABLED", "payload": boolean } | { "type": "TOGGLE_BOOK", "payload": number } | { "type": "TOGGLE_ALL_BOOKS", "payload": boolean } | { "type": "SET_LOADING", "payload": boolean } | { "type": "SET_ERROR", "payload": string | null } | { "type": "SET_VIEWED_BOOK", "payload": number | null } | { "type": "SET_PROCESSING", "payload": boolean } | { "type": "SET_PROCESSING_PROGRESS", "payload": ProcessingProgress } | { "type": "CLEAR_PROCESSING_PROGRESS" } | { "type": "ADD_LOG_ENTRY", "payload": LogEntryPayload } | { "type": "CLEAR_LOG" } | { "type": "SET_GIT_SYNC_STATUS", "payload": GitSyncStatus } | { "type": "SET_GIT_AUTH_STATUS", "payload": GitAuthStatus } | { "type": "SET_COMMIT_HISTORY", "payload": Array<GitCommit> } | { "type": "GIT_OPERATION_STARTED" } | { "type": "GIT_OPERATION_COMPLETED", "payload": { success: boolean, message: string, } } | { "type": "DEVICE_FLOW_STARTED", "payload": DeviceFlowInfo } | { "type": "DEVICE_FLOW_COMPLETED", "payload": { success: boolean, } };
