// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookMetadata } from "./BookMetadata";
import type { BookPath } from "./BookPath";

/**
 * Information about a book file
 */
export type BookInfo = { path: BookPath, display_name: string, selected: boolean, cover_image_path: string | null, metadata: BookMetadata | null, };
