// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Book metadata from YAML frontmatter
 */
export type BookMetadata = { title: string, author: string, "belongs-to-collection": string | null, "group-position": number | null, language: string | null, rights: string | null, "cover-image": string | null, };
