// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookInfo } from "./BookInfo";

/**
 * Result of changing a book's source file
 */
export type ChangeBookResult = { new_book_path: string, books: Array<BookInfo>, updated_book_index: number | null, };
