// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cover image data for sending to frontend
 */
export type CoverImageData = { 
/**
 * Base64-encoded data URL (e.g., "data:image/png;base64,...")
 */
data_url: string, 
/**
 * Image width in pixels
 */
width: number, 
/**
 * Image height in pixels
 */
height: number, };
