// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GitHub Device Flow information for UI display
 */
export type DeviceFlowInfo = { 
/**
 * Device code (internal, not shown to user)
 */
deviceCode: string, 
/**
 * User code to enter in browser
 */
userCode: string, 
/**
 * URL where user should authorize
 */
verificationUri: string, 
/**
 * Seconds until code expires
 */
expiresIn: bigint, };
