// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GitHub authentication status for UI
 */
export type GitAuthStatus = { "status": "NotAuthenticated" } | { "status": "Authenticated" } | { "status": "TokenExpired" };
