// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Git synchronization status for UI display
 */
export type GitSyncStatus = { "status": "Uninitialized" } | { "status": "Clean" } | { "status": "NeedsPush" } | { "status": "NeedsPull" } | { "status": "Dirty" };
