// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogEntryType } from "./LogEntryType";

/**
 * Log entry data without timestamp
 */
export type LogEntryPayload = { message: string, type: LogEntryType, };
