// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Events emitted during book processing (serializable for Tauri events)
 */
export type ProcessingEvent = { "type": "started", book_index: number, book_name: string, } | { "type": "completed", book_index: number, success: boolean, message: string, top_words: Array<[string, number]> | null, } | { "type": "all_done" };
