// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress state for batch processing
 */
export type ProcessingProgress = { currentBookIndex: number, currentBookName: string, };
