// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * NewType wrapper for publish checkbox state
 */
export type PublishEnabled = boolean;
