// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookPath } from "./BookPath";
import type { FolderPath } from "./FolderPath";
import type { PublishEnabled } from "./PublishEnabled";
import type { WordStatsEnabled } from "./WordStatsEnabled";

/**
 * Session data to persist between application runs
 */
export type SessionData = { 
/**
 * Last selected folder path
 */
folder_path: FolderPath, 
/**
 * Publish enabled checkbox state
 */
publish_enabled: PublishEnabled, 
/**
 * Word stats enabled checkbox state
 */
word_stats_enabled: WordStatsEnabled, 
/**
 * Paths of books that were selected
 */
selected_book_paths: Array<BookPath>, };
