// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookInfo } from "./BookInfo";
import type { PublishEnabled } from "./PublishEnabled";
import type { WordStatsEnabled } from "./WordStatsEnabled";

/**
 * Overall UI state
 */
export type UiState = { books: Array<BookInfo>, publish_enabled: PublishEnabled, word_stats_enabled: WordStatsEnabled, };
